apiVersion: v1
kind: Service
metadata:
  labels:    #selects Pods
    app: review-service-h2
  name: review-service-h2
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30207
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: review-service-h2
  sessionAffinity: None   #None, ClientIP
  type: LoadBalancer